Add april planning session
tomeshnet/tomesh.net pull request #143
Opened 2017-04-08 15:02 UTC by dcwalk

2017-04-09 07:14 UTC, benhylau requested changes

2017-04-09 07:14 UTC, benhylau commented on _posts/2017-04-26-planning-session.md
> +Join us at our fourth planning session, where we regroup and plan for the summer! At this session we set priorities and projects and form form **working groups** for the next six months and identify
form form

2017-04-12 01:02 UTC, garrying requested changes
I think we are leaning to the 24th as the new date?

2017-04-13 02:26 UTC, dcwalk commented
Made the changes @garrying and @benhylau merge when ready. I'll be able to add to the Civic Tech calendar, announce, etc... when live.

2017-04-13 04:06 UTC, benhylau approved these changes

2017-04-13 04:07 UTC, merged