Added May 18, 2017 Install Party event
tomeshnet/tomesh.net pull request #144
Opened 2017-05-02 01:29 UTC by dasanchez

Merged the most recent hack night + monthly check-in events into one.

2017-05-02 03:09 UTC, benhylau commented on _posts/2017-05-18-install-party.md
> +date: 2017-05-18
Are we not doing one this Thursday on the 4th?

2017-05-02 11:52 UTC, dasanchez commented on _posts/2017-05-18-install-party.md
> +date: 2017-05-18
Right! We agreed on a monthly install party and a biweekly hardware (node.tech) meeting at the last planning session-
I understand the one on the 4th is more of a hardware meeting, so should I add it as such? I figure the calendar would end up looking something like:
- May 04 - node.tech
- May 18 - install party/check-in
- Jun 01 - node.tech
- Jun 15 - node.tech
- Jun 29 - install party/check-in
Thoughts?

2017-05-03 04:51 UTC, benhylau commented on _posts/2017-05-18-install-party.md
> +date: 2017-05-18
Oh I thought it was:

May 04 - install party/check-in
May 18 - virtual
Jun 01 - install party/check-in
Jun 15 - virtual

See: https://github.com/tomeshnet/documents/commit/ba2938db12cc25257f3f0ee685d7f3087f261490#diff-b127bd3696cae846707a960e8bed6a7cR80

node.tech are also bi-weekly, but separate from the above, and the first one will be on May 11:

https://github.com/tomeshnet/documents/commit/ba2938db12cc25257f3f0ee685d7f3087f261490#diff-b127bd3696cae846707a960e8bed6a7cR190

2017-05-03 11:58 UTC, dasanchez commented
I adjusted the dates for all three events coming up this month:
- Monthly install party
- Biweekly node.tech meeting
- Biweekly virtual mesh session

2017-05-03 12:02 UTC, dasanchez commented on _posts/2017-05-18-install-party.md
> +date: 2017-05-18
Sorry for the confusion! I made a new commit

2017-05-03 13:53 UTC, dcwalk commented
We might want to ignore those flakey links (https://github.com/gjtorikian/html-proofer#ignoring-content) for future PRs? I can submit as a separate one

2017-05-03 13:54 UTC, dcwalk commented
Also -- just to clarify @benhylau all of the in person events are happening at Semaphore studio?

2017-05-03 13:56 UTC, dcwalk commented on _posts/2017-06-01-install-party.md
> +date: 2017-06-01
I'd suggest bumping this back a week...? and having the June events follow suit

2017-05-03 14:01 UTC, dcwalk commented on _posts/2017-05-04-install-party.md
> +text: 'tomesh monthly install party and social'
This shows up in the description so maybe something a little differentiated from the title?

"Bring your equipment to set up a mesh node" (or something?)

2017-05-03 14:02 UTC, dcwalk reviewed
Some minor suggestions

2017-05-03 14:02 UTC, dcwalk commented on _posts/2017-05-04-install-party.md
> +Join us at {{page.startTime | date:"%-I:%M%P "}} on {{ page.date | date: '%B %d, %Y' }} for our monthly install party and working groups' check-in. This month we will be meeting at [{{ page.location
I'd remove the "working groups'" part? As I think this is more about installing stuff?

2017-05-03 14:03 UTC, dcwalk commented on _posts/2017-05-11-node-tech.md
> +slug: node-tech-night
Maybe drop 'night' from the slug? might be confusing to have a different word.

2017-05-03 15:15 UTC, benhylau requested changes

2017-05-03 15:15 UTC, benhylau commented on _posts/2017-05-04-install-party.md
> +Join us at {{page.startTime | date:"%-I:%M%P "}} on {{ page.date | date: '%B %d, %Y' }} for our monthly install party and working groups' check-in. This month we will be meeting at [{{ page.location
But we said we'd do working group check-in during drinks. Maybe:

>Join us at {{page.startTime | date:"%-I:%M%P "}} on {{ page.date | date: '%B %d, %Y' }} for our monthly install party and play with distributed applications. This month we will be meeting at [{{ page.location }}]({{ page.locationLink }}) for a hands-on session before heading to a nearby bar for drinks and progress check with each working group.

2017-05-03 15:15 UTC, benhylau commented on _posts/2017-05-04-install-party.md
> +endTime: '20:30'
More like 23:00 if we do the social.

2017-05-03 15:15 UTC, benhylau commented on _posts/2017-05-11-node-tech.md
> +slug: node-tech-night
We should just drop all the `node.tech` meetings from calendar.

2017-05-03 15:15 UTC, benhylau commented on _posts/2017-05-25-node-tech.md
> +---
Drop.

2017-05-03 15:15 UTC, benhylau commented on _posts/2017-05-18-virtual-mesh.md
> +Although the [cjdns mesh software](https://github.com/cjdelisle/cjdns) runs on multiple platforms, most people are [running it on a Raspberry Pi](https://github.com/tomeshnet/prototype-cjdns-pi2). No
https://github.com/tomeshnet/prototype-cjdns-pi now

2017-05-03 15:15 UTC, benhylau commented on _posts/2017-06-01-install-party.md
> +date: 2017-06-01
The date is correct I think? 2 weeks from last virtual mesh.

2017-05-03 17:33 UTC, dcwalk commented on _posts/2017-06-01-install-party.md
> +date: 2017-06-01
June is a long month. We periodically reset/added a week to keep us in the same week-of-month over the last year

2017-05-03 17:35 UTC, dcwalk commented on _posts/2017-05-11-node-tech.md
> +slug: node-tech-night
If you know if it a standing meeting and it is open for people to join, why wouldn't you have them in?

2017-05-03 23:49 UTC, dasanchez commented on _posts/2017-05-04-install-party.md
> +text: 'tomesh monthly install party and social'
Changed

2017-05-03 23:50 UTC, dasanchez commented on _posts/2017-05-04-install-party.md
> +Join us at {{page.startTime | date:"%-I:%M%P "}} on {{ page.date | date: '%B %d, %Y' }} for our monthly install party and working groups' check-in. This month we will be meeting at [{{ page.location
Changed to benhylau's text

2017-05-03 23:50 UTC, dasanchez commented on _posts/2017-05-11-node-tech.md
> +slug: node-tech-night
I just took them out for now

2017-05-03 23:50 UTC, dasanchez commented on _posts/2017-05-04-install-party.md
> +endTime: '20:30'
23:00, done

2017-05-03 23:50 UTC, dasanchez commented on _posts/2017-05-25-node-tech.md
> +---
Gone

2017-05-03 23:50 UTC, dasanchez commented on _posts/2017-05-18-virtual-mesh.md
> +Although the [cjdns mesh software](https://github.com/cjdelisle/cjdns) runs on multiple platforms, most people are [running it on a Raspberry Pi](https://github.com/tomeshnet/prototype-cjdns-pi2). No
Updated

2017-05-05 00:40 UTC, benhylau approved these changes

2017-05-08 01:08 UTC, merged