Date Updates
tomeshnet/tomesh.net pull request #147
Opened 2017-06-21 03:03 UTC by Shrinks99

Auto updates the footer for the website and fixes the date on the README.md file.

2017-06-21 03:08 UTC, benhylau commented on _includes/footer.html
> +        <p> &copy;<script>new Date().getFullYear()>2010&&document.write(" "+new Date().getFullYear());</script>, Toronto Mesh. Our <a href="/code-of-conduct/">Code of Conduct</a>.<br />This website c
@garrying @dcwalk I think we prefer generating this into static text with jekyll than js? That can be done right?

2017-06-21 03:33 UTC, garrying requested changes

2017-06-21 03:33 UTC, garrying commented on _includes/footer.html
> +        <p> &copy;<script>new Date().getFullYear()>2010&&document.write(" "+new Date().getFullYear());</script>, Toronto Mesh. Our <a href="/code-of-conduct/">Code of Conduct</a>.<br />This website c
Yeah. The JS can be `{{ 'now' | date: "%Y" }}`.  @Shrinks99 Thanks for catching this!

2017-06-21 04:29 UTC, Shrinks99 commented on _includes/footer.html
> +        <p> &copy;<script>new Date().getFullYear()>2010&&document.write(" "+new Date().getFullYear());</script>, Toronto Mesh. Our <a href="/code-of-conduct/">Code of Conduct</a>.<br />This website c
Much better solution!

2017-06-22 02:59 UTC, garrying approved these changes

2017-06-22 17:07 UTC, benhylau approved these changes

2017-06-22 17:07 UTC, merged