Google Map Positioning
tomeshnet/tomesh.net pull request #197
Opened 2017-12-15 21:45 UTC by darkdrgn2k

CSS Hack to allow google map interface to work like "natural" and  prevent things like  require  CTRL+SCROLL to zoom.

Scroll bar still allows for the scrolling of the page as do arrows to see footer.

Please confirm on your os/browser of choice if there are any issues.

2017-12-16 19:17 UTC, garrying requested changes
Can we revise this to something more general purpose—add a front matter prop to hide the footer on specific pages?

2017-12-16 19:58 UTC, Shrinks99 commented
Would be in favour of hiding the footer on the map page.

2017-12-17 01:04 UTC, darkdrgn2k commented
To be clear i'm not actually HIDDeING the footer 

You can still see if by scrolling using the right scroll bard, using the arrows on the keyboard or using the "Scroll" feature on the mouse as long as the mouse is not positioned over the map.

As for dropping the footer instead to this patch, I'm fine with either or.

2017-12-18 00:50 UTC, garrying commented
@darkdrgn2k what i was thinking of: 62cfce2397dd04ff357b6fbaa375ede74eab41ab

2017-12-22 17:44 UTC, merged